kind: Pod
apiVersion: v1
metadata:
  name: nginx-liveness-pod
spec:
  containers:
  - name: nginx-container
    image: nginx:1.14
    livenessProbe:
      httpGet:
        path: /
        port: 80
      failureThreshold: 3
      periodSeconds: 30
      successThreshold: 1
      timeoutSeconds: 3
    ports:
    - containerPort: 80
