apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: sts-nginx
spec:
  replicas: 3
  serviceName: sts-service
  podManagementPolicy: Parallel
  selector:
    matchLabels:
      app: mysts
  template:
    metadata:
      name: nginx-pod
      labels:
        app: mysts
    spec:
      containers:
      - name: nginx-container
        image: nginx:1.14
